spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rs_system?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  jpa:
    hibernate:
      ddl-auto: create
